### ISSUE TITLE
v0.5 checklist

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/architecture-documentation#34]
Format: The main team pulling an item is at the heading of the list. The item is preceeded by the component followed by the item description and optionally a reference to a github issue.

## Project-wide (architecture)
- [x] Cloud / architecture / mapeditor / NWN-DTK: User defined postfix on OMOTES job results (requires changes from JobSubmission all the way to workers and back) https://github.com/Project-OMOTES/architecture-documentation/issues/35
- [x] Cloud / architecture / mapeditor / NWN-DTK: Integrate simulator https://github.com/Project-OMOTES/architecture-documentation/issues/33
- [x] Cloud / architecture / mapeditor / NWN-DTK: Settle on new influxdb format for ESDL profiles https://github.com/Project-OMOTES/architecture-documentation/issues/31

## Cloud
- [x] Orchestrator, workers & SDK: Fix issue where worker may also send out ProgressUpdate 0.0 which has special meaning for orchestrator as it may trigger a cancellation on the job due to delivery limit. https://github.com/Project-OMOTES/omotes-sdk-python/pull/85/files
- [x] Optimizer worker: Test if new Casadi version fixes issue with threading
- [x] Optimizer worker: New optimizer version in optimizer-worker.
  - [x] https://github.com/Multi-Energy-Systems-Optimization/mesido/pull/174 will have consequences to how mesido should be called.
- [x] Simulator-worker: Integrate progress function: https://github.com/Project-OMOTES/simulator-worker/issues/28
- [x] Simulator-worker: New version of simulator-core in simulator-worker. https://github.com/Project-OMOTES/simulator-worker/issues/27
- [x] Simulator-worker: Fix issue regarding asset ids and port ids https://github.com/Project-OMOTES/simulator-worker/pull/33
- [x] OMOTES-system: Update simulator-worker version to newest release.
- [x] Simulator-worker: Write out influxdb data in new format: https://github.com/Project-OMOTES/simulator-worker/issues/25
- [x] Simulator-worker, optimizer-worker, orchestrator, python-SDK: Alter JobSubmission to contain a job reference and alter output ESDL name at the workers.
    - [x] https://github.com/Project-OMOTES/simulator-worker/pull/30
    - [x] https://github.com/Project-OMOTES/optimizer-worker/pull/78
    - [x] https://github.com/Project-OMOTES/orchestrator/pull/71
    - [x] https://github.com/Project-OMOTES/omotes-sdk-python/pull/77
    - [x] https://github.com/Project-OMOTES/omotes-sdk-protocol/pull/21
    - [x] https://github.com/Project-OMOTES/omotes-system/pull/106
    - [x] https://github.com/Project-OMOTES/omotes-rest/pull/38

## Optimizer
- [x] Optimizer: Workflow cleanup. This has an impact on the way the workflow is called (<-- changes on optimizer worker required).  https://github.com/Multi-Energy-Systems-Optimization/mesido/pull/174
- [x] Optimizer: limit available pipe classes for a pipe connected to a heat demand. https://github.com/Multi-Energy-Systems-Optimization/mesido/pull/155
- [x] Optimizer: pandapipes validation test case. https://github.com/Multi-Energy-Systems-Optimization/mesido/pull/169
- [x] Optimizer: update the min velocity. https://github.com/Multi-Energy-Systems-Optimization/mesido/pull/170
- [x] Optimizer: error checks to be updated. https://github.com/Multi-Energy-Systems-Optimization/mesido/issues/151
- [x] Optimizer: fix profile parsing and scaling of the ATES. https://github.com/Multi-Energy-Systems-Optimization/mesido/pull/173
- [ ] Optimizer: code quality, scaling checks in test cases [Add scaling check to every test · Issue #140 · Multi-Energy-Systems-Optimization/mesido (github.com)](https://github.com/Multi-Energy-Systems-Optimization/mesido/issues/140) - **this is not part of MESIDO v0.1.8.1 and has been put on hold for now**
- [ ] Optimizer: updated documentation for discounted cost calculation **- this is not part of MESIDO v0.1.8.1, aim will be to incorporate this in the next update of this release** 
- [x] All of the above in a new mesido release

## TPG
- [ ] Typescript SDK: Update typescript SDK to become compatible with newest version of OMOTES
  - [x] https://github.com/Project-OMOTES/typescript-sdk/issues/11
  - [x] https://github.com/Project-OMOTES/typescript-sdk/issues/10
  - [x] https://github.com/Project-OMOTES/typescript-sdk/issues/9
  - [x] https://github.com/Project-OMOTES/typescript-sdk/issues/8
  - [x] https://github.com/Project-OMOTES/typescript-sdk/issues/12
  - [x] https://github.com/Project-OMOTES/typescript-sdk/issues/13
  - [x] https://github.com/Project-OMOTES/typescript-sdk/issues/14
  - [x] https://github.com/Project-OMOTES/typescript-sdk/issues/20
  - [ ] https://github.com/Project-OMOTES/typescript-sdk/issues/28
- [ ] NWN-DTK: integrate a new field to request the job reference from a user
- [ ] NWN-DTK/typescript: Connect simulator to NWN-DTK frontend. https://github.com/Project-OMOTES/architecture-documentation/issues/33
- [x] NWN-DTK: New influxdb format for writing results simulator worker to influxdb.  https://github.com/Project-OMOTES/architecture-documentation/issues/31

## MapEditor
- [x] Mapeditor: Animations based on timeseries profiles
- [x] Mapeditor: integrate a new field to request the job reference from a user
- [x] Mapeditor: show generic feedback messages (not relating to a specific asset)

## Simulator
- [x] simulator-core: Results available in front end. (Michiel)
- [x] simulator-core: Coupling with Rosim for the ATES. This might require some adjustments from the container for the simulator since Rossim is a JAVA mode. (Ryvo & Mark) 
- [x] simulator-core: Simple controller based on priority. Ideally priority is added to ESDL for producers, if it is not already available. Optimizer uses Marginal costs, but I would like to avoid this. 
- [x] simulator-core: Improvements in code and speed ups.
- [x] All of the above in a new simulator-core version.
- [x] Documentation on read the docs (https://simulator-core.readthedocs.io/en/latest/index.html) 

# Late so ASAP after v0.5 or during buffer week:
## Optimizer
- [ ] Update Casadi to 3.7 and test if this version works as expected. (Align with rtc-tools)

## Cloud
- [ ] Update optimizer-worker with new version of optimizer once new Casadi version is in.
- [ ] Optimizer-worker: Casadi fix (optimizer needs to be updated and work with newest casadi version)  https://github.com/Project-OMOTES/optimizer-worker/issues/57

# Stretch goals v0.5:
## Project-wide (architecture)
- [x] Standardized error messages from optimizer/simulator to frontend https://github.com/Project-OMOTES/architecture-documentation/issues/38
- [ ] Gurobi support for optimizer https://github.com/Project-OMOTES/architecture-documentation/issues/8

## Simulator
- [ ] simulator-core: Possible we manage to add a heat pump, but we are not sure if we will manage
